add additional checks to verify dist is latest

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -24,3 +24,12 @@ jobs:
     - name: Run ESLint
       run: yarn lint # -- --max-warnings 0
 
+    - name: Build
+      run: yarn build
+
+    - name: Check dist files are up to date
+      run: |
+        if [ -n "$(git status --porcelain dist)" ]; then
+            echo "error: dist files are not up to date"
+            exit 1
+        fi
