dist files fix

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -27,9 +27,9 @@ jobs:
     - name: Build
       run: yarn build
 
-    # - name: Check dist files are up to date
-    #   run: |
-    #     if [ -n "$(git status --porcelain dist)" ]; then
-    #         echo "error: dist files are not up to date"
-    #         exit 1
-    #     fi
+    - name: Check dist files are up to date
+      run: |
+        if [ -n "$(git status --porcelain dist)" ]; then
+            echo "error: dist files are not up to date"
+            exit 1
+        fi
